name: keyboard_dismisser
description: A simple Flutter package to hide the keyboard when performing a gesture outside of it.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

